### ISSUE TITLE
Ignore archived repositories

### ISSUE THREAD

**Issue by raunaqgupta** [zenclabs/prmonitor#149]
Similar to #65 but since archived repos don't have functioning PRs anyway, better to ignore them outright.

**Comment by fwouts** [comment]
Thanks for the suggestion, indeed that makes sense!

Feel free to send a PR, I suspect it's a simple change here: https://github.com/zenclabs/prmonitor/blob/master/src/github-api/implementation.ts#L15

Otherwise I'll try and get to it in a few days 😊
