### ISSUE TITLE
Show a notification when your own PR is ready to merge

### ISSUE THREAD

**Issue by fwouts** [zenclabs/prmonitor#160]
But make it possible to disable notifications, as these aren't urgent and therefore there's no need to break flow.

**Comment by mdvorsky** [comment]
Notification may be easy to miss, however a new tab "My ready-to-merge PRs" (Similar to "Incoming" vs "Already reviewed") would be useful.

**Comment by fwouts** [comment]
Agree, both would be useful!

One thing I'd be curious about from your perspective: if you have multiple reviewers assigned, and one of them approved, do you consider that enough to consider the PR ready to merge? Or would you wait until everyone has approved?

**Comment by mdvorsky** [comment]
That depends, but typically we merge based on what github allows. Can't merge when it says "Review required", merge when it says "Changes approved".
