### ISSUE TITLE
Green badge when 0 active PRs is obnoxious

### ISSUE THREAD

**Issue by michaelpearce-at** [zenclabs/prmonitor#225]
When there are 0 active PRs, the extension icon has a badge with `0` on a green background in white text. It's particularly hard to read, and doesn't match other extensions. I would either make it grey, or remove it entirely when there are 0.

<img width="145" alt="Screen Shot 2019-06-03 at 3 30 42 pm" src="https://user-images.githubusercontent.com/33816671/58778203-f4709e80-8614-11e9-9445-1487abc757a4.png">

**Comment by fwouts** [comment]
That's fair. I'd rather change the colour so it's clear that you have zero (instead of wondering whether PR Monitor is broken).

It's a one-line change: https://github.com/zenclabs/prmonitor/blob/master/src/badge/implementation.ts#L39

Do you have a hex code handy? Feel free to send a PR.
